handofolio/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portofolio/', include("portofolio.urls", namespace='portofolio')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portofolio/urls.py
from django.conf.urls import url
from django.contrib import admin


from .views import(
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)


urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

portofolio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone

from django.utils.text import slugify

# Create your models here.
class PortoManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PortoManager, self) #.filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)


class Portofol(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	image = models.ImageField(upload_to=upload_location)
	slug = models.SlugField(unique=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	objects = PortoManager()


	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("portofolio:detail", kwargs={"slug": self.slug})

	class Meta:
		ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Portofol.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Portofol)

portofolio/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Portofol

class PortoForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget) # widget untuk form date publish

	class Meta:
		model = Portofol
		fields = [
			"title",
			"content",
			"image",
			]

portofolio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

# Create your views here.
from .forms import PortoForm
from .models import Portofol


# Create your views here.
def post_create(request):
	form = PortoForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
        # messages success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	else:
		messages.error(request, "Not Successfully Messages")

	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)
	#return HttpResponse("<h1>Hello Create!</h1>")

def post_detail(request, slug=None): # retrieve
	instance = get_object_or_404(Portofol, slug=slug)
	if instance.publish > timezone.now().date():
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
    #share_string = quote_plus(instance.content)
	context = {
		"title": instance.title,
		"instance":instance,
    #    "share_string": share_string,
	}
	return render(request, "post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Portofol.objects.all()
	#if request.user.is_staff or request.user.is_superuser:
	#	queryset_list = Portofol.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query)|
				Q(user__last_name__icontains=query)
				).distinct()

	paginator = Paginator(queryset_list , 6) # Show 6 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
		"object_list": queryset,
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}

	return render(request, "post_list.html", context)
	#return HttpResponse("<h1>Hello List!!</h1>")

def post_update(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	form = PortoForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
        # messages success
	messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
	return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance":instance,
		"form":form,
	}
	return render(request, "post_form.html", context)
	#return HttpResponse("<h1>Hello Update!!</h1>")

def post_delete(request, id=None):
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully Deleted")
	return redirect("portofolio:list")
	r#eturn HttpResponse("<h1>Hello Delete!!</h1>")

portofolio/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
    {% block style %}
    {% endblock style %}
    </style>
    <link rel="stylesheet" href="{% static 'css/flexboxgrid.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" />

    <title>{% block head_title %}portofolio{% endblock %}</title>
  </head>
  <body>
    <!-- header -->
    <header id="main-header">
     <div class="container">
      <div class="row end-sm end-md end-lg center-xs middle-xs middle-sm middle-md middle-lg">
       <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
       	<h1><span class="primary-text">Hando</span>Folio</h1>
       </div>
       <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
       	<nav id="navbar">
    	   <ul>
    		   <li class="current"><a href="">Home</a></li>
    		   <li><a href="">About</a></li>
    		   <li><a href="">Services</a></li>
    		   <li><a href="">Contact</a></li>
    	   </ul>
       	</nav>
       </div>
      </div>
      </div>
    </header>

    <!-- showcase -->
    <section id="showcase">
     <div class="container">
      <div class="row center-xs center-sm center-md center-lg midle-xs midle-sm midle-md midle-lg">
       <div class="col-xs-10 col-sm-10 col-md-9 col-lg-7 showcase-content">
       	<h1>Welcome to <span class="primary-text">My Portofolio</span></h1>
       	 <p>A template built with html5, CSS3 and flexboxgrid</p>
       	</div>
      </div>
     </div>
    </section>

    <!-- features -->
    <section id="features">
      <div class="container">
        {% block content %}

        {% endblock content %}
      </div>
    </section>


    <!-- info section -->
    <section id="info">
    	<div class="container">
    		<div class="row center-xs center-sm center-md center-lg middle-xs middle-sm middle-md middle-lg">
    			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    				<img src="images/iphone.jpg" alt="">
    			</div>
    			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    				<h2>Core Features</h2>
    				<ul>
    					<li><i class="fa fa-check"></i> Fully Optimized</li>
    					<li><i class="fa fa-check"></i> Free Support</li>
    					<li><i class="fa fa-check"></i> Free Upgrade</li>
    					<li><i class="fa fa-check"></i> Uptime Guarantee</li>
    					<li><i class="fa fa-check"></i> Multiple User/li>
    					<li><i class="fa fa-check"></i> Plug & Play</li>
    				</ul>
    			</div>
    		</div>
    	</div>
    </section>


    <!-- company -->
    <section id="company">
    	<div class="container">
    		<div class="row">
    			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    				<h4>Contact Us</h4>
    				<ul>
    					<li><i class="fa fa-phone"></i> (+62-821) 555-555</li>
    					<li><i class="fa fa-envelope"></i> support@mail.com</li>
    					<li><i class="fa fa-map"></i> 400 main st, Bumiayu</li>
    				</ul>
    			</div>
    			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    				<h4>About Us</h4>
    				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    			</div>
    			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    				<h4>Newsletter</h4>
    				<p>Lorem ipsum dolor sit amet</p>
    				<form>
    					<input type="text" name="email" value="" placeholder="Enter Email">
    					<button type="submit" name="button">Submit</button>
    				</form>
    			</div>
    		</div>
    	</div>
    </section>

    <!-- footer -->
    <footer id="main-footer">
    	<div class="container">
    		<div class="row center-xs center-sm center-md center-lg">
    			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    				<p>Copyright &copy; 2017 | AppTheme</p>
    			</div>
    		</div>
    	</div>
    </footer>


    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<!-- script js untuk membuat markdown -->
  <script type="text/javascript">
    $(document).ready(function(){
      $(".content-markdown").each(function(){
          var content = $(this).text()
          var markedContent = marked(content)
          $(this).html(markedContent)
        })
      $(".post-detail-item img").each(function(){
          $(this).addClass("img-responsive");
        })

      // preview-title
      var titleInput = $("#id_title");

      function setTitle(value) {
        $("#preview-title").text(value)
      }
      setTitle(titleInput.val())

      titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
      })


      // $("#preview-content").html(marked(contentItem.val()))
      var contentInput = $("#id_content");

      function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
          $(this).addClass("img-responsive")
        })
      }
      setContent(contentInput.val())

      contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
      })

  })
  </script>

  
  </body>
</html>

portofolio/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}


{% block content %}
<div class="row">
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<h1>Preview</h1>
<hr/>
<div class="content-preview">
	<h3 id="preview-title"></h3>
	<p id="preview-content"></p>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<h1>Form</h1>
<hr/>
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
</div>
{% endblock content %}

portofolio/templates/post_list.html
{% extends "base.html" %}
{% block content %}

<!---->

    <br>
    <div class="row center-xs center-md center-lg">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>Portofolio</h2>
          <br>
            <div class="row center-xs center-md center-lg">
              {% for obj in object_list %}
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">{{ obj.title }}</h2>
                    <p class="lead">{{ obj.content }}</p>
                </div>
                <div class="col-md-6">
                {% if obj.image %}
                    <img class="img-responsive" src="{{ obj.image.url }}" alt="">
                {% endif %}
                </div>
              {% endfor %}
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->
    <div class="pagination">
      <span class="step-links">
          {% if object_list.has_previous %}
              <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
          </span>

          {% if object_list.has_next %}
              <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
          {% endif %}
      </span>
  	</div>


{% endblock content %}